services:
  oxidized:
    # Choose the image that you want to test
    # image: docker.io/oxidized/oxidized:0.30.1
    # image: docker.io/oxidized/oxidized:latest
    # local/oxidized is build by "make oxidized-image" and "make run"
    image: local/oxidized
    ports:
      - 127.0.0.1:8042:8888/tcp
    environment:
      # Reload hosts list once per day
      CONFIG_RELOAD_INTERVAL: 86400
      # Needed when you push to a remote git repository
      OXIDIZED_SSH_PASSPHRASE: xxxxPassphasexxxx
    volumes:
       - ./oxidized-config:/home/oxidized/.config/oxidized
       - ./oxidized-ssh:/home/oxidized/.ssh

  # This is a simulated network device for the example to work out of the box
  asternos-device:
    image: localhost/local/model
    volumes:
      - ./model-simulation/asternos.sh:/home/oxidized/.profile
      - ./model-simulation/asternos.sh:/home/admin/.profile

  # This is a gitserver to push our configs
  gitserver:
    image: localhost/local/gitserver
    volumes:
      - ./gitserver/repo.git:/home/git/repo.git
